### ISSUE TITLE
模板工程下载安装后运行 npm run prerender 报错

### ISSUE THREAD

**Issue by softshield** [umijs/umi-example-ssr-with-egg#14]
运行npm run prerender    Nodejs报错：
```

(node:6708) UnhandledPromiseRejectionWarning: AssertionError [ERR_ASSERTION]: Invalid key locale from plugin
    at C:\workspace\home\umi-example-ssr-with-egg\app\public\umi.server.js:1:10035
    at Array.forEach (<anonymous>)
    at Object.h [as use] (C:\workspace\home\umi-example-ssr-with-egg\app\public\umi.server.js:1:10002)
    at Object.EBG0 (C:\workspace\home\umi-example-ssr-with-egg\app\public\umi.server.js:1:19815)
    at n (C:\workspace\home\umi-example-ssr-with-egg\app\public\umi.server.js:1:124)
    at Object.0 (C:\workspace\home\umi-example-ssr-with-egg\app\public\umi.server.js:1:11295)
    at n (C:\workspace\home\umi-example-ssr-with-egg\app\public\umi.server.js:1:124)
    at module.exports.+IuP.Object.defineProperty.value (C:\workspace\home\umi-example-ssr-with-egg\app\public\umi.server.js:1:929)
    at Object.<anonymous> (C:\workspace\home\umi-example-ssr-with-egg\app\public\umi.server.js:1:938)
    at Module._compile (module.js:653:30)
    at Module._compile (C:\workspace\home\umi-example-ssr-with-egg\node_modules\_pirates@4.0.1@pirates\lib\index.js:99:24)
    at Module._extensions..js (module.js:664:10)
    at Object.newLoader [as .js] (C:\workspace\home\umi-example-ssr-with-egg\node_modules\_pirates@4.0.1@pirates\lib\index.js:104:7)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
(node:6708) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:6708) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

运行 npm  start  浏览器报错，页面能显示：

```
Uncaught (in promise) ReferenceError: react is not defined
    at Object.zIXN (umi.3fcbf9d9.js:1)
    at n (umi.3fcbf9d9.js:1)
    at Object.+rCz (umi.3fcbf9d9.js:1)
    at n (umi.3fcbf9d9.js:1)
    at Object.fnp/ (umi.3fcbf9d9.js:1)
    at n (umi.3fcbf9d9.js:1)
    at umi.3fcbf9d9.js:1
    at l (umi.3fcbf9d9.js:1)
    at Generator._invoke (umi.3fcbf9d9.js:1)
    at Generator.e.(:7001/anonymous function) [as next] (http://localhost:7001/public/umi.3fcbf9d9.js:1:493611)

```

**Comment by jin-benben** [comment]
能说一下为什么关闭issue吗，我也是刚clone的项目，运行之后同样的报错，

**Comment by ycjcl868** [comment]
重新 pull 下，就 ok 了
