### ISSUE TITLE
yarn start error

### ISSUE THREAD

**Issue by xiaohuoni** [umijs/umi-example-ssr-with-egg#3]
```
$ npm start

> egg-umi-ssr-demo@1.0.0 start /Users/xiaohuoni/Documents/GitHub/umi-example-ssr-with-egg
> egg-scripts start --daemon --env prod

[egg-scripts] Starting egg application at /Users/xiaohuoni/Documents/GitHub/umi-example-ssr-with-egg
[egg-scripts] Run node /Users/xiaohuoni/Documents/GitHub/umi-example-ssr-with-egg/node_modules/egg-scripts/lib/start-cluster {"baseDir":"/Users/xiaohuoni/Documents/GitHub/umi-example-ssr-with-egg","framework":"/Users/xiaohuoni/Documents/GitHub/umi-example-ssr-with-egg/node_modules/egg","title":"egg-server-egg-umi-ssr-demo"} --title=egg-server-egg-umi-ssr-demo
[egg-scripts] Save log file to /Users/xiaohuoni/logs
[egg-scripts] Wait Start: 1...
[egg-scripts] Wait Start: 2...
[egg-scripts] Wait Start: 3...
[egg-scripts] tail -n 100 /Users/xiaohuoni/logs/master-stderr.log
[egg-scripts] Got error when startup: 
[egg-scripts]     at AppWorkerLoader.loadCustomApp (/Users/xiaohuoni/Documents/GitHub/umi-example-ssr-with-egg/node_modules/egg-core/lib/loader/mixin/custom.js:37:20)
[egg-scripts]     at AppWorkerLoader.load (/Users/xiaohuoni/Documents/GitHub/umi-example-ssr-with-egg/node_modules/egg/lib/loader/app_worker_loader.js:35:10)
[egg-scripts]     at new Application (/Users/xiaohuoni/Documents/GitHub/umi-example-ssr-with-egg/node_modules/egg/lib/application.js:66:19)
[egg-scripts]     at Object.<anonymous> (/Users/xiaohuoni/Documents/GitHub/umi-example-ssr-with-egg/node_modules/egg-cluster/lib/app_worker.js:19:13)
[egg-scripts]     at Module._compile (internal/modules/cjs/loader.js:688:30)
[egg-scripts]     at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
[egg-scripts] /Users/xiaohuoni/Documents/GitHub/umi-example-ssr-with-egg/node_modules/egg/lib/application.js:70
[egg-scripts]       throw e;
[egg-scripts]       ^
[egg-scripts] 
[egg-scripts] AssertionError [ERR_ASSERTION]: /Users/xiaohuoni/Documents/GitHub/umi-example-ssr-with-egg/config/manifest.json is required
[egg-scripts]     at module.exports.app (/Users/xiaohuoni/Documents/GitHub/umi-example-ssr-with-egg/node_modules/egg-view-assets/app.js:28:5)
[egg-scripts]     at Hook.configDidLoad (/Users/xiaohuoni/Documents/GitHub/umi-example-ssr-with-egg/node_modules/egg-core/lib/lifecycle.js:92:9)
[egg-scripts]     at Lifecycle.triggerConfigDidLoad (/Users/xiaohuoni/Documents/GitHub/umi-example-ssr-with-egg/node_modules/egg-core/lib/lifecycle.js:143:14)
[egg-scripts]     at Lifecycle.triggerConfigWillLoad (/Users/xiaohuoni/Documents/GitHub/umi-example-ssr-with-egg/node_modules/egg-core/lib/lifecycle.js:137:10)
[egg-scripts]     at AppWorkerLoader.loadCustomApp (/Users/xiaohuoni/Documents/GitHub/umi-example-ssr-with-egg/node_modules/egg-core/lib/loader/mixin/custom.js:37:20)
[egg-scripts]     at AppWorkerLoader.load (/Users/xiaohuoni/Documents/GitHub/umi-example-ssr-with-egg/node_modules/egg/lib/loader/app_worker_loader.js:35:10)
[egg-scripts]     at new Application (/Users/xiaohuoni/Documents/GitHub/umi-example-ssr-with-egg/node_modules/egg/lib/application.js:66:19)
[egg-scripts]     at Object.<anonymous> (/Users/xiaohuoni/Documents/GitHub/umi-example-ssr-with-egg/node_modules/egg-cluster/lib/app_worker.js:19:13)
```

**Comment by ycjcl868** [comment]
看起来是要配置 manifest

**Comment by williamnie** [comment]
这是因为，egg在启动时，要去config下面找manifest.json文件，在umi的配置内需要开启manifest的配置，现在我是使用umi buildSuccess的api，每次build以后，自动复制到egg的config文件夹下面。
解决方案：**_（仅供参考，我的目录结构和demo不一样）_**
1.需要在umi的config里面配置manifest
`
 manifest: {
    fileName: 'manifest.json',
  },
`
2.在umi的config里面配置自己的plugin
`
plugins.push(['./config/copyMainfastToConfig.js', {}]);
方式可能不同，仅供参考，请查看umi官网
`
3.plugin的代码如下（仅供参考，与demo路径不一样）
```
import fs from 'fs';
import process from 'process';

export default function (api, options = {}) {

  // 这个从插件是用来copy mainfast文件建立连接的，勿删！！

  // add by elivoa - fix break analyze.
  if (process.env.ANALYZE) {
    console.log(' ANALYZE MODE ')
    return
  }

  api.onBuildSuccess(({ stats }) => {
    const rmfile = (path) => {
      let files = [];
      if (fs.existsSync(path)) {
        files = fs.readdirSync(path);
        for (const file of files) {
          const curPath = `${path}/${file}`;
          if (fs.statSync(curPath).isDirectory()) {
            rmfile(curPath);
          } else {
            fs.unlinkSync(curPath);
          }
        }
        fs.rmdirSync(path);
      }
    };
    const dirname = fs.readdirSync('config');
    if (dirname.includes('manifest.json')) {
      fs.unlinkSync('config/manifest.json');
      fs.renameSync('app/public/manifest.json', 'config/manifest.json');
    } else {
      fs.renameSync('app/public/manifest.json', 'config/manifest.json');
    }
    process.exit()
  });
}

```
